version: 2

project_name: go-kweb-lang

before:
  hooks:
    - go mod tidy

builds:
  - id: go-kweb-lang
    main: ./cmd/main.go
    binary: go-kweb-lang
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default_archives
    ids:
      - go-kweb-lang
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: github
