// Code generated by MockGen. DO NOT EDIT.
// Source: pullreq.go
//
// Generated by this command:
//
//	mockgen -typed -source=pullreq.go -destination=./internal/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	github "github.com/dkarczmarski/go-kweb-lang/github"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHub is a mock of GitHub interface.
type MockGitHub struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubMockRecorder
	isgomock struct{}
}

// MockGitHubMockRecorder is the mock recorder for MockGitHub.
type MockGitHubMockRecorder struct {
	mock *MockGitHub
}

// NewMockGitHub creates a new mock instance.
func NewMockGitHub(ctrl *gomock.Controller) *MockGitHub {
	mock := &MockGitHub{ctrl: ctrl}
	mock.recorder = &MockGitHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHub) EXPECT() *MockGitHubMockRecorder {
	return m.recorder
}

// GetCommitFiles mocks base method.
func (m *MockGitHub) GetCommitFiles(ctx context.Context, commitID string) (*github.CommitFiles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitFiles", ctx, commitID)
	ret0, _ := ret[0].(*github.CommitFiles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitFiles indicates an expected call of GetCommitFiles.
func (mr *MockGitHubMockRecorder) GetCommitFiles(ctx, commitID any) *MockGitHubGetCommitFilesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitFiles", reflect.TypeOf((*MockGitHub)(nil).GetCommitFiles), ctx, commitID)
	return &MockGitHubGetCommitFilesCall{Call: call}
}

// MockGitHubGetCommitFilesCall wrap *gomock.Call
type MockGitHubGetCommitFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitHubGetCommitFilesCall) Return(arg0 *github.CommitFiles, arg1 error) *MockGitHubGetCommitFilesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitHubGetCommitFilesCall) Do(f func(context.Context, string) (*github.CommitFiles, error)) *MockGitHubGetCommitFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitHubGetCommitFilesCall) DoAndReturn(f func(context.Context, string) (*github.CommitFiles, error)) *MockGitHubGetCommitFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPRCommits mocks base method.
func (m *MockGitHub) GetPRCommits(ctx context.Context, prNumber int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRCommits", ctx, prNumber)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRCommits indicates an expected call of GetPRCommits.
func (mr *MockGitHubMockRecorder) GetPRCommits(ctx, prNumber any) *MockGitHubGetPRCommitsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRCommits", reflect.TypeOf((*MockGitHub)(nil).GetPRCommits), ctx, prNumber)
	return &MockGitHubGetPRCommitsCall{Call: call}
}

// MockGitHubGetPRCommitsCall wrap *gomock.Call
type MockGitHubGetPRCommitsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitHubGetPRCommitsCall) Return(arg0 []string, arg1 error) *MockGitHubGetPRCommitsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitHubGetPRCommitsCall) Do(f func(context.Context, int) ([]string, error)) *MockGitHubGetPRCommitsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitHubGetPRCommitsCall) DoAndReturn(f func(context.Context, int) ([]string, error)) *MockGitHubGetPRCommitsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PRSearch mocks base method.
func (m *MockGitHub) PRSearch(ctx context.Context, filter github.PRSearchFilter, page github.PageRequest) (*github.PRSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRSearch", ctx, filter, page)
	ret0, _ := ret[0].(*github.PRSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRSearch indicates an expected call of PRSearch.
func (mr *MockGitHubMockRecorder) PRSearch(ctx, filter, page any) *MockGitHubPRSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRSearch", reflect.TypeOf((*MockGitHub)(nil).PRSearch), ctx, filter, page)
	return &MockGitHubPRSearchCall{Call: call}
}

// MockGitHubPRSearchCall wrap *gomock.Call
type MockGitHubPRSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitHubPRSearchCall) Return(arg0 *github.PRSearchResult, arg1 error) *MockGitHubPRSearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitHubPRSearchCall) Do(f func(context.Context, github.PRSearchFilter, github.PageRequest) (*github.PRSearchResult, error)) *MockGitHubPRSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitHubPRSearchCall) DoAndReturn(f func(context.Context, github.PRSearchFilter, github.PageRequest) (*github.PRSearchResult, error)) *MockGitHubPRSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCacheStorage is a mock of CacheStorage interface.
type MockCacheStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCacheStorageMockRecorder
	isgomock struct{}
}

// MockCacheStorageMockRecorder is the mock recorder for MockCacheStorage.
type MockCacheStorageMockRecorder struct {
	mock *MockCacheStorage
}

// NewMockCacheStorage creates a new mock instance.
func NewMockCacheStorage(ctrl *gomock.Controller) *MockCacheStorage {
	mock := &MockCacheStorage{ctrl: ctrl}
	mock.recorder = &MockCacheStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheStorage) EXPECT() *MockCacheStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCacheStorage) Delete(bucket, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", bucket, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheStorageMockRecorder) Delete(bucket, key any) *MockCacheStorageDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheStorage)(nil).Delete), bucket, key)
	return &MockCacheStorageDeleteCall{Call: call}
}

// MockCacheStorageDeleteCall wrap *gomock.Call
type MockCacheStorageDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheStorageDeleteCall) Return(arg0 error) *MockCacheStorageDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheStorageDeleteCall) Do(f func(string, string) error) *MockCacheStorageDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheStorageDeleteCall) DoAndReturn(f func(string, string) error) *MockCacheStorageDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockCacheStorage) Read(bucket, key string, buff any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", bucket, key, buff)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockCacheStorageMockRecorder) Read(bucket, key, buff any) *MockCacheStorageReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockCacheStorage)(nil).Read), bucket, key, buff)
	return &MockCacheStorageReadCall{Call: call}
}

// MockCacheStorageReadCall wrap *gomock.Call
type MockCacheStorageReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheStorageReadCall) Return(arg0 bool, arg1 error) *MockCacheStorageReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheStorageReadCall) Do(f func(string, string, any) (bool, error)) *MockCacheStorageReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheStorageReadCall) DoAndReturn(f func(string, string, any) (bool, error)) *MockCacheStorageReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *MockCacheStorage) Write(bucket, key string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", bucket, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockCacheStorageMockRecorder) Write(bucket, key, data any) *MockCacheStorageWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockCacheStorage)(nil).Write), bucket, key, data)
	return &MockCacheStorageWriteCall{Call: call}
}

// MockCacheStorageWriteCall wrap *gomock.Call
type MockCacheStorageWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheStorageWriteCall) Return(arg0 error) *MockCacheStorageWriteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheStorageWriteCall) Do(f func(string, string, any) error) *MockCacheStorageWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheStorageWriteCall) DoAndReturn(f func(string, string, any) error) *MockCacheStorageWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
